AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - lib/tasks/*
    - test/**/*
    - vendor/**/*
    - Gemfile
    - Rakefile
    - config.ru

  TargetRubyVersion: 2.5

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 21

Naming/AccessorMethodName:
  Exclude:
    - app/controllers/devise_token_auth/custom_omniauth_callbacks_controller.rb

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - app/views/*/*.jbuilder

Style/RaiseArgs:
  Enabled: false
