# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_client_id: <%= ENV['APOLLO_GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['APOLLO_GOOGLE_CLIENT_SECRET'] %>
  google_static_maps_key: <%= ENV['APOLLO_GOOGLE_STATIC_MAPS_KEY'] %>
  cloudinary_key: <%= ENV['APOLLO_CLOUDINARY_KEY'] %>
  cloudinary_secret: <%= ENV['APOLLO_CLOUDINARY_SECRET'] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d0d87c380a0e67d67a3c3705f4362ec0f52647874c3992dce265e6b211150c3163c556fd9321ac8bb732e246b1f588af0b9fc9daa06a798695d07fda0476f55
  devise_key: c8632b407e90991d73df9d4b2073693bea932b154e8ff4e1ef066527849fbbdabed19abee74b6ed9518135a6fcdd4ee2abf867c3ae2b3e91bc95727a7a4aca3e

test:
  secret_key_base: 54f1108d942c4884ad440064085bda0ba468caaeedc01f299f2732011c3180027180c7306341f1e7b2c7b725e00684b2d262e2e85def45a9119088bf5f2d5d71
  devise_key: a0cfff93b5644bc9b1e0e521696e04a735e746aba80a2e8fa8379495657a37a4175d312d846ecd4defed55fde5d04112894161536da5d584f2b1957e7e631cb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV['APOLLO_SECRET_KEY'] %>
  devise_key: <%= ENV['APOLLO_DEVISE_KEY'] %>
  sidekiq_username: <%= ENV['SIDEKIQ_USERNAME'] %>
  sidekiq_password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  new_relic_key: <%= ENV['NEW_RELIC_KEY'] %>
  raven_key: <%= ENV['RAVEN_KEY'] %>
  raven_secret: <%= ENV['RAVEN_SECRET'] %>
  raven_id: <%= ENV['RAVEN_ID'] %>
